apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-trainer
    app.kubernetes.io/part-of: modela
    app.kubernetes.io/component: operator
  name: modela-trainer
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-trainer
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-trainer
    spec:
      containers:
        - name: main
          image: gcr.io/modela/modela-trainer:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: data
              mountPath: /var/data
        - name: sidecar
          image: ghcr.io/metaprov/modela-cloud-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3001
          volumeMounts:
              - name: data
                mountPath: /var/data
      volumes:
        - name : data
          emptyDir: {}