apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-trainer-metrics
    app.kubernetes.io/part-of: modela
    app.kubernetes.io/component: metrics
  name: modela-trainer-metrics
  namespace: modela-system
spec:
  ports:
    - name: metrics
      protocol: TCP
      port: 8082
      targetPort: 8082
  selector:
    app.kubernetes.io/name: modela-trainer