apiVersion: infra.modela.ai/v1alpha1
kind: License
metadata:
  name: default-license
  namespace: modela-system
spec:
  secretRef: 
    name: default-license-secret
    namespace: modela-system
  email: ""
  maxProducts: 5
  maxTrainers: 1
  maxServers:  3
  maxUsers: 1
  maxDataPlanes: 1
  forecast: true
  nlp: false
  vision: false
  chatbot: false
  productName: "modela.ai free"
  priceName: "lite"
  notifierName:  default-email-notifier
