apiVersion: data.modela.ai/v1alpha1
kind: DataProduct
metadata:
  namespace: default-tenant
  name: default-product
spec:
  color: blue
  cacheBucketName: default-minio-bucket
  defaultBucketName: default-minio-bucket
  defaultServingSiteName: default-serving-site
  defaultLabName: default-lab
  task: binary-classification  
  trainingResources:
    workloadName: general-large
  servingResources:
    workloadName: general-large
  owner: admin
  notification:
    ttl: 3600
    notifierName: "default-slack-notifier"
  permissions:
    accounts:
      - accountName: admin
        roles:
          - name: administrator


