apiVersion: management.modela.ai/v1alpha1
kind: Modela
metadata:
  name: modela-sample
spec:
  observability:
    prometheus: false
    prometheusChartVersion: "0.57.0"
    loki: false
    lokiChartVersion: "2.8.4"
  modelaChart:
    installed: true
    chartVersion: "v0.4.866"  
  defaultTenantChart: 
    installed : true
    chartVersion: "v0.4.866"
  objectStore:
    installed: false
    minioChartVersion: "9.2.9"
  certManager:
    installed: false
    chartVersion: "v1.7.1"
  systemDatabase:
    installed: false
    postgresChartVersion: "10.9.2"
  controlPlane:
    replicas: 1
  dataPlane:
    replicas: 1
  apiGateway:
    replicas: 1
