apiVersion: v1
kind: Secret
metadata:
  name: default-postgres-secret
  namespace: default-tenant
type: Opaque
stringData:
  username: 'postgres'
  password: 'KDecXDZTih'    
---

apiVersion: infra.modela.ai/v1alpha1
kind: Connection
metadata:
  name: default-postgres-connection
  namespace: default-tenant  
spec:
  owner: admin
  provider: postgres
  category: database
  tenantRef:
    name: default-tenant
    namespace: modela-system
  secretRef:
    name: default-postgres-secret
    namespace: default-tenant
  postgres:
    host: 'modela-postgresql.modela-system.svc.cluster.local'
    port: 5432
    username: 'postgres'
    password: ''
    database: 'postgres'    
    url: ''   
