apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: modela-predictor
    app.kubernetes.io/part-of: modela
    app.kubernetes.io/component: modela-predictor
  name: modela-predictor
  namespace: modela-system
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - get
      - list
      - watch
