apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modela-predictor
    app.kubernetes.io/part-of: modela
    app.kubernetes.io/component: data
  name: modela-predictor
  namespace: modela-system