apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-data-dock
  name: modela-data-dock
  namespace: modela-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8095
  selector:
    app.kubernetes.io/name: modela-data-dock