apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-online-store
    app.kubernetes.io/part-of: modela
  name: modela-online-store
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-online-store
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-online-store
    spec:
      containers:
        - name: main
          image: ghcr.io/metaprov/modela-online-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
          resources:
            limits:
              cpu: "200m"
              memory: 512Mi
            requests:
              cpu: "100m"
              memory: 256Mi    
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8092"]
            initialDelaySeconds: 60
          livenessProbe:
              exec:
                command: ["/bin/grpc_health_probe", "-addr=:8092"]
              initialDelaySeconds: 60
          env:
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DEBUG
              value: "true"
            - name: ENV
              value:  "dev"
            - name: CACHE_PATH
              value: "/var/opt/modela/data"
            - name: CLOUDS_HOST
              value: "127.0.0.1"
            - name: CLOUDS_PORT
              value: "8090"
