apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-api-gateway
    app.kubernetes.io/part-of: modela
  name: modela-api-gateway
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: modela-api-gateway