apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-api-gateway
    app.kubernetes.io/part-of: modela
  name: modela-api-gateway
spec:
  ports:
    - name: grpc
      port: 8080
    - name: http
      port: 8081
  selector:
    app.kubernetes.io/name: modela-api-gateway