# permissions for end users to edit modelaconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelaconfiguration-editor-role
rules:
- apiGroups:
  - core.modela.ai
  resources:
  - modelaconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.modela.ai
  resources:
  - modelaconfigurations/status
  verbs:
  - get
