# permissions for end users to view modelabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelabackup-viewer-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups/status
  verbs:
  - get
