# permissions for end users to view modelabackupruns.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelabackuprun-viewer-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackupruns
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackupruns/status
  verbs:
  - get
