# permissions for end users to view modelaconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelaconfiguration-viewer-role
rules:
- apiGroups:
  - core.modela.ai
  resources:
  - modelaconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.modela.ai
  resources:
  - modelaconfigurations/status
  verbs:
  - get
