# permissions for end users to edit modelas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modela-editor-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelas/status
  verbs:
  - get
