# permissions for end users to view modelas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modela-viewer-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelas/status
  verbs:
  - get
