# permissions for end users to edit modelabackups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelabackup-editor-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups/status
  verbs:
  - get
