---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackupruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackupruns/finalizers
  verbs:
  - update
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackupruns/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups/finalizers
  verbs:
  - update
- apiGroups:
  - management.modela.ai
  resources:
  - modelabackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - management.modela.ai
  resources:
  - modelas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - management.modela.ai
  resources:
  - modelas/finalizers
  verbs:
  - update
- apiGroups:
  - management.modela.ai
  resources:
  - modelas/status
  verbs:
  - get
  - patch
  - update
