apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-medium
  namespace: modela-catalog
spec:
  resourcesTemplate:
    cpuImage:
      name:  modela-cpu-trainer-latest
      namespace: modela-catalog 
    gpuImage:
      name:  modela-gpu-trainer-latest
      namespace: modela-catalog       
    requirements:
        requests:
          memory: "256Mi"
          cpu: "0.5"
        limits:
          memory: "512Mi"
          cpu: "1"  
  
  