apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-large
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "512Mi"
        cpu: "1.5"
      limits:
        memory: "1024Mi"
        cpu: "2"  
