apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: compute-2xlarge
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "512Mi"
        cpu: "2"
      limits:
        memory: "1024Mi"
        cpu: "3"  
  