apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: general-small
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "128Mi"
        cpu: "250m"
      limits:
        memory: "256Mi"
        cpu: "500m" 