apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: general-large
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1024Mi"
        cpu: "1024m"  