apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: memory-2xlarge
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "1500Mi"
        cpu: "0.5"
      limits:
        memory: "2000Mi"
        cpu: "1"  