apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: memory-xlarge
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "2048Mi"
        cpu: "1"
      limits:
        memory: "2048Mi"
        cpu: "2"