apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: memory-medium
  namespace: modela-catalog
spec:
  resourcesTemplate:
    cpuImage:
      name:  modela-cpu-trainer-latest
      namespace: modela-catalog 
    gpuImage:
      name:  modela-gpu-trainer-latest
      namespace: modela-catalog       
    requirements:
      requests:
        memory: "512Mi"
        cpu: "0.25"
      limits:
        memory: "1024Mi"
        cpu: "0.5"    