apiVersion: catalog.modela.ai/v1alpha1
kind: WorkloadClass
metadata:
  name: memory-large
  namespace: modela-catalog
spec:
  resourcesTemplate:
    requirements:
      requests:
        memory: "1024Mi"
        cpu: "0.5"
      limits:
        memory: "2048Mi"
        cpu: "1"  