## Append samples you want in your CSV to this file as resources ##
resources:
- management_v1alpha1_modela.yaml
- management_v1alpha1_modelabackuprun.yaml
- management_v1alpha1_modelabackup.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
