# Install Modela with all Helm Charts enabled
apiVersion: management.modela.ai/v1alpha1
kind: Modela
metadata:
  name: modela
  namespace: modela-system
spec:
  distribution: 'develop'
  certManager:
    install: true
  objectStore:
    install: true
  observability:
    installPrometheus: false
    installLoki: false
    installGrafana: false
  tenants:
    - name: 'modela'
      adminPassword: 'admin'