apiVersion: management.modela.ai/v1alpha1
kind: Modela
metadata:
  name: modela
  namespace: modela-system
spec:
  distribution: 'develop'
  certManager:
    install: true
  objectStore:
    install: true
  database:
    installPgvector: false
    installMongoDB: false
  vault:
    install: true
    mountPath: 'modela/secrets'
  tenants:
    - name: 'modela'