# Install Modela with all Helm Charts enabled
apiVersion: management.modela.ai/v1alpha1
kind: Modela
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx

  name: modela
  namespace: modela-system
spec:
  distribution: 'develop'
  certManager:
    install: true
  objectStore:
    install: true
  observability:
    installPrometheus: true
    installLoki: true
    installGrafana: true
  tenants:
    - name: 'modela'
      adminPassword: 'admin'
  ingress:
    enabled: true
    installNginx: true
    hostname: 'localhost'
