apiVersion: infra.modela.ai/v1alpha1
kind: Tenant
metadata:
  name: default-tenant
  namespace: modela-system
spec:
  cacheBucketName: default-minio-bucket
  defaultLabName: default-lab
  defaultServingSiteName: default-serving-site
  defaultBucketName: default-minio-bucket
  permissions:
    accounts:
      - accountName: admin
        roles:
          - name: administrator
