apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: extreme-randomized-tree
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  frameworkName: scikit-learn
  task: binary-classification