apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: sgd-regressor
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  frameworkName: scikit-learn
  task: regression
  categoricalParameters:
    - name: loss
      enums:
        - hinge
        - log
        - modified_huber
        - squared_hinge
        - perceptron
      defaultValue: log
    - name: penalty
      enums:
        - l1
        - l2
        - elasticnet
      defaultValue: l2
    - name: learning_rate
      enums:
        - optimal
        - invscaling
        - constant
      defaultValue: invscaling
  floatParameters:
      - name: alpha        
        min: 1e-7
        max: 0.1
        log: True
        defaultValue: 0.0001
      - name: l1_ratio
        min: 1e-9
        max: 1
        log: True
        defaultValue: 0.15
      - name: tol
        min: 1e-5
        max: 0.1
        log: True
        defaultValue: 1e-4
      - name: epsilon
        min: 1e-5
        max: 0.1
        defaultValue: 1e-4
        log: True
      - name: eta0        
        min: 1e-7
        max: 0.1
        defaultValue: 0.01
        log: True
      - name: power_t
        min: 1e-5
        max: 1
        defaultValue: 0.5
