apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: logistic-regression-classifier
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  task: binary-classification
  frameworkName: scikit-learn