apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: decision-tree-classifier
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  task: binary-classification
  frameworkName: scikit-learn
  integerParameters:
    - name:   min_samples_split
      min: 2
      max: 20
      defaultValue: 2
    - name:   min_samples_leaf
      min: 1
      max: 20
      defaultValue: 1
  categoricalParameters:
    - name:  criterion      
      enums:
       - gini
       - entropy
      defaultValue:  gini
    - name:  splitter
      enums:
       - best
       - random
      defaultValue:  best







