apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: svm-classifier
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  frameworkName: scikit-learn
  task: binary-classification
  floatParameters:
    - name: C
      log: true
      min: 0.03125
      max: 32768
      defaultValue: 1.0
    - name: gamma
      log: true
      min: 3.0517578125e-05
      max: 8
      defaultValue: 0.1
    - name: tol
      log: true
      min: 1e-5
      max: 1e-1
  categoricalParameters:
    - name: kernel
      defaultValue: rbf
      enums:
         - rbf
         - poly
         - sigmoid
  integerParameters:
    - name: degree
      min: 2
      max: 5
      defaultValue: 3
    - name : coef0
      min:  -1
      max:   1
      defaultValue: 0
