apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  name: linear-svc-classifier
  namespace: modela-catalog
  labels:
    app.kubernetes.io/part-of: modela
spec:
  frameworkName: scikit-learn
  task: binary-classification
  categoricalParameters:
    - name: penalty
      enums:
      -  l1
      -  l2
      defaultValue: l2
    - name: loss
      enums:
        - hinge
        - squared_hinge
      defaultValue: squared_hinge
  floatParameters:
    - name: tol
      min: 1e-5
      max: 1e-1
      defaultValue: 1e-4
      log: True
    - name: C
      min: 0.03125
      max: 32768
      defaultValue: 1.0
      log: True
