apiVersion: infra.modela.ai/v1alpha1
kind: Account
metadata:
  name: admin
  namespace: default-tenant
spec:
  admin: true
  tenantRef:
    name: default-tenant
    namespace: modela-system
  type: "user"
  username: "admin"
  firstName: "admin"
  lastName: "admin"
 
