apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-api-proxy
  name: modela-api-proxy
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-api-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-api-proxy
    spec:
      serviceAccountName: modela-api-proxy
      containers:
        - name: main
          image: ghcr.io/metaprov/modela-api-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: grpc
            - containerPort: 8008
              name: profiling
          resources:
            limits:
              cpu: "200m"
              memory: 128Mi
            requests:
              cpu: "100m"
              memory: 64Mi
          