apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-api-proxy
  name: modela-api-proxy
  namespace: modela-system
spec:
  ports:
    - name: grpc
      port: 8080
  selector:
    app.kubernetes.io/name: modela-api-proxy
