apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: modela-system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: serving-cert
  namespace: modela-system
spec:
  dnsNames:
    - modela-control-plane-webhook.svc.cluster.local
    - modela-control-plane-webhook.modela-system.svc
    - modela-control-plane-webhook
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: webhook-server-cert
