apiVersion: v1
kind: ConfigMap
metadata:
   name: modela-config
   namespace: modela-system
data:
  release: develop
  vaultAddress: http://modela-vault.modela-system.svc.cluster.local:8200
  vaultMountPath: modela/secrets
  imagePullPolicy: Always
  cachePath: "/var/opt/modela/data"
