apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-control-plane
    app.kubernetes.io/part-of: modela
  name: modela-control-plane
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-control-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-control-plane
    spec:
      serviceAccountName: modela-control-plane
      containers:
        - name: main
          image: ghcr.io/metaprov/modela-control-plane:develop
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data
              mountPath: /var/opt/modela/data
            - name: webhook-server-cert
              mountPath: /tmp/k8s-webhook-server/serving-certs
              readOnly: true
          env:
            - name: CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: modela-config
                  key: cachePath
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
            - containerPort: 6060
              name: pprof
          resources:
            limits:
              cpu: "1000m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
        - name: clouds
          image: ghcr.io/metaprov/modela-cloud-proxy:develop
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
          volumeMounts:
            - name: data
              mountPath: /var/opt/modela/data
          env:
            - name: CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: modela-config
                  key: cachePath
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8090" ]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8090" ]
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: data
          emptyDir: { }
        - name: webhook-server-cert
          secret:
            secretName: webhook-server-cert