apiVersion: v1
kind: ClusterServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: modela-control-plane
    app.kubernetes.io/part-of: modela
  name: modela-job-runner
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: modela-control-plane
    app.kubernetes.io/part-of: modela
  name: modela-job-runner
  namespace: modela-system
rules:
  - apiGroups: ["batch"]
    resources:
      - job
    verbs: ["*"]
  - apiGroups: [""]
    resources:
      - jobs
      - pods
    verbs:
      - get
      - create
      - list
      - watch
      - update
      - delete
