apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#  Adds namespace to all resources.
namespace: modela-system

resources:
  - ./deployment.yaml
  - ./metrics.yaml
  - ./rbac.yaml
  - ./webhook-service.yaml
  - ./webhook-validation-configuration.yaml
  - ./webhook-mutation-configuration.yaml
  - ./configmap.yaml
  - ./certificates.yaml
