apiVersion: infra.modela.ai/v1alpha1
kind: ModelaSystem
metadata:
  name: system
  namespace: modela-system
spec:
  release: v0.4.350
  active: true  
  podTemplate:
      metadata: 
        labels:
          app.kubernetes.io/name: modela-trainer
      spec:
        restartPolicy: Never
        containers:
          - name: control
            ports:
                - containerPort: 8080
            volumeMounts:
                - name: data
                  mountPath: /var/opt/modela/data
          - name: data
            image: ghcr.io/metaprov/modela-data-plane:v0.4.205
            imagePullPolicy: IfNotPresent
            ports:
               - containerPort: 8070
                 name: http
               - containerPort: 9090
                 name: metrics
               - containerPort: 8008
                 name: profiling
            resources:
              requests:
                memory: "512Mi"
                cpu: "200m"
              limits:
                memory: "1Gi"
                cpu: "1"
            volumeMounts:
               - name: data
                 mountPath: /var/opt/modela/data
          - name: cloud-proxy
            image: ghcr.io/metaprov/modela-cloud-proxy:latest
            imagePullPolicy: IfNotPresent
            ports:
              - name: http
                containerPort: 8090
            volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
        volumes:
          - name: data
            emptyDir: {}