apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-data-plane
    app.kubernetes.io/part-of: modela
  name: modela-data-plane
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-data-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-data-plane
    spec:
      serviceAccountName: modela-data-plane
      containers:
        - name: main
          image: ghcr.io/metaprov/modela-data-plane:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /var/opt/modela/data
          resources:
            limits:
              cpu: "1000m"
              memory: 2048Mi
            requests:
              cpu: "100m"
              memory: 512Mi
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: modela-config
                  key: cachePath
        - name: clouds
          image: ghcr.io/metaprov/modela-cloud-proxy:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8090
          volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
          env:
            - name: CACHE_PATH
              valueFrom:
                configMapKeyRef:
                  name: modela-config
                  key: cachePath
          readinessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8090" ]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: [ "/bin/grpc_health_probe", "-addr=:8090" ]
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: "100m"
              memory: "128Mi"
            requests:
              cpu: "50m"
              memory: "64Mi"
      volumes:
        - name : data
          emptyDir: {}