apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: modela-data-plane
    app.kubernetes.io/part-of: modela
  name: modela-data-plane
  namespace: modela-system
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: modela-data-plane
  template:
    metadata:
      labels:
        app.kubernetes.io/name: modela-data-plane
    spec:
      serviceAccountName: modela-data-plane
      containers:
        - name: main
          image: ghcr.io/metaprov/modela-data-plane:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 9090
              name: metrics
            - containerPort: 8008
              name: profiling
          volumeMounts:
            - name: data
              mountPath: /var/opt/modela/data
          resources:
            limits:
              cpu: "200m"
              memory: 512Mi
            requests:
              cpu: "100m"
              memory: 256Mi    
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8080"]
            initialDelaySeconds: 60
          livenessProbe:
              exec:
                command: ["/bin/grpc_health_probe", "-addr=:8080"]
              initialDelaySeconds: 60
          env:
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8080"
            - name: DEBUG
              value: "true"
            - name: ENV
              value:  "dev"
            - name: CACHE_PATH
              value: "/var/opt/modela/data"
            - name: CLOUDS_HOST
              value: "127.0.0.1"
            - name: CLOUDS_PORT
              value: "8090"



        - name: clouds
          image: ghcr.io/metaprov/modela-cloud-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - name: grpc
              containerPort: 8090
          volumeMounts:
              - name: data
                mountPath: /var/opt/modela/data
          readinessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 60
          livenessProbe:
            exec:
              command: ["/bin/grpc_health_probe", "-addr=:8090"]
            initialDelaySeconds: 60
          resources:
            limits:
              cpu: "200m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"  
          env:
            - name: HOST
              value:  "0.0.0.0"
            - name: PORT
              value: "8090"
            - name: DEBUG
              value: "true"
            - name: ENV
              value:  "dev"
            - name: CACHE_PATH
              value: "/var/opt/modela/data"
      volumes:
        - name : data
          emptyDir: {}