apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

#  Adds namespace to all resources.
namespace: modela-system

resources:
  - ./deployment.yaml
  - ./service.yaml
  - ./metrics.yaml
  - ./rbac.yaml

