apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: modela-data-plane
    app.kubernetes.io/part-of: modela
  name: modela-data-plane
  namespace: modela-system
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: modela-data-plane