name: Lint and Test Charts

on: [push]

jobs:
   lint-chart:
      runs-on: ubuntu-latest
      steps:
              - name: Checkout
                uses: actions/checkout@v1
              - name: Run chart-testing (lint)
                uses: helm/chart-testing-action@master
                with:
                  command: lint
                  config: .github/ct.yaml
   lint-docs:
     runs-on: ubuntu-latest
     needs: lint-chart
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: Run helm-docs
         run: .github/helm-docs.sh

   publish:
     runs-on: ubuntu-latest
     needs: lint-docs
     steps:
       - uses: actions/checkout@v1
       - uses: J12934/helm-gh-pages-action@master
         with:
           access-token: ${{ secrets.ACCESS_TOKEN }}

   release:
     runs-on: ubuntu-latest
     needs: publish
     steps:
       - name: Checkout
         uses: actions/checkout@v1
       - name: Configure Git
         run: |
           git config user.name "$GITHUB_ACTOR"
           git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
       - name: Run chart-releaser
         uses: helm/chart-releaser-action@master
         env:
           CR_TOKEN: '${{ secrets.ACCESS_TOKEN }}'