apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: ada-boost-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 200
    low: 100
    name: ada_n_estimators
    type: int
  - high: 2.0
    log: true
    low: 0.01
    name: ada_learning_rate
    type: float
  tasks: []

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: bernoulli-nb
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 100
    log: true
    low: 0.01
    name: br_alpha
    type: float
  - choices:
    - "true"
    - "false"
    name: br_fit_prior
    type: categorical
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: catboost-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 12
    low: 1
    name: catboost_depth
    type: int
  - high: 1.0
    log: true
    low: 0.02
    name: catboost_learning_rate
    type: float
  - choices:
    - Bayesian
    - Bernoulli
    - MVS
    name: catboost_bootstrap_type
    type: categorical
  - choices:
    - Plain
    - Ordered
    name: catboost_boosting_type
    type: categorical
  - high: 100
    low: 10
    name: catboost_iterations
    type: int
  - high: 10
    low: 0
    name: catboost_bagging_temperature
    type: float
  - high: 1
    low: 0.1
    name: catboost_subsample
    type: float
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: decision-tree-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - choices:
    - gini
    - entropy
    name: criterion
    type: categorical
  - high: 10
    low: 4
    name: dt_max_depth
    type: int
  - high: 20
    low: 2
    name: dt_min_samples_split
    type: int
  - high: 20
    low: 1
    name: dt_min_samples_leaf
    type: int
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: extra-tree-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 20
    low: 2
    name: et_min_samples_split
    type: int
  - high: 1.0
    log: true
    low: 0.1
    name: et_max_features
    type: float
  - high: 20
    low: 1
    name: et_min_samples_leaf
    type: int
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: gaussian-nb
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges: []
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: gradient-boosting-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 0.2
    log: true
    low: 0.001
    name: gb_learning_rate
    type: float
  - high: 200
    low: 100
    name: gb_n_estimators
    type: int
  - high: 7
    low: 2
    name: gb_max_leaf_nodes
    type: int
  - high: 9
    low: 1
    name: gb_min_samples_leaf
    type: int
  - high: 10
    low: 4
    name: gb_max_depth
    type: int
  - high: 10
    low: 2
    name: gb_min_samples_split
    type: int
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: hist-gradient-boosting
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 0.2
    log: true
    low: 0.001
    name: hg_learning_rate
    type: float
  - high: 200
    low: 100
    name: hg_max_iter
    type: int
  - high: 7
    low: 2
    name: hg_max_leaf_nodes
    type: int
  - high: 9
    low: 1
    name: hg_min_samples_leaf
    type: int
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: knn-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 20
    low: 1
    name: knn_n_neighbors
    type: int
  - choices:
    - uniform
    - distance
    name: knn_weights
    type: categorical
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: linear-discriminant
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges: []
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: lightgbm-classifier
  namespace: modela-catalog
spec:
  frameworkName: lightgbm
  ranges:
  - choices:
    - gbdt
    - dart
    name: lgbm_boosting_type
    type: categorical
  - high: 10
    low: 4
    name: lgbm_max_depth
    type: int
  - high: 1.0
    log: true
    low: 0.02
    name: lgbm_learning_rate
    type: float
  - high: 150
    low: 50
    name: lgbm_n_estimators
    type: int
  - high: 0.01
    low: 0.001
    name: lgbm_min_child_weight
    type: float
  - high: 30
    low: 5
    name: lgbm_min_child_samples
    type: int
  - high: 1
    log: true
    low: 0.01
    name: lgbm_subsample
    type: float
  - high: 5
    low: 0
    name: lgbm_subsample_freq
    type: int
  - high: 1.0
    log: true
    low: 0.01
    name: lgbm_colsample_bytree
    type: float
  - high: 1.0
    log: true
    low: 0.0
    name: lgbm_reg_alpha
    type: float
  - high: 1.0
    log: true
    low: 0.0
    name: lgbm_reg_lambda
    type: float
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: linear-svc
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 32768
    log: true
    low: 0.03125
    name: svc_C
    type: float
  - high: 5
    low: 2
    name: svc_degree
    type: int
  - high: 8
    log: true
    low: 3.0517578125e-05
    name: svc_gamma
    type: float
  - high: 1
    log: true
    low: -1
    name: svc_coef0
    type: float
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: logistic-regression
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - choices:
    - newton-cg
    - lbfgs
    - liblinear
    - sag
    - saga
    name: logreg_solver
    type: categorical
  - choices:
    - none
    - l2
    name: logreg_penalty_cg
    type: categorical
  - choices:
    - none
    - l2
    name: logreg_penalty_lbfgs
    type: categorical
  - choices:
    - l2
    - l1
    name: logreg_penalty_liblinear
    type: categorical
  - choices:
    - none
    - l2
    name: logreg_penalty_sag
    type: categorical
  - choices:
    - elasticnet
    - l1
    - l2
    - none
    name: logreg_saga
    type: categorical
  - choices:
    - "true"
    - "false"
    name: logreg_dual
    type: categorical
  - high: 1.0
    log: true
    low: 0
    name: logreg_l1_ratio
    type: float
  - high: 10.0
    log: true
    low: 1.0e-07
    name: logreg_C
    type: float
  - choices:
    - "true"
    - "false"
    name: logreg_fit_intercept
    type: categorical
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: multinomial-nb
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 100
    log: true
    low: 0.01
    name: multinb_alpha
    type: float
  - choices:
    - "true"
    - "false"
    name: multinb_fit_prior
    type: categorical
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: passive-aggressive-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 10
    log: true
    low: 0.03125
    name: pa_C
    type: float
  - choices:
    - hinge
    - squared_hinge
    name: pa_loss
    type: categorical
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: random-forest-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 2000
    low: 200
    name: rf_n_estimators
    type: int
  - high: 20
    low: 2
    name: rf_min_samples_split
    type: int
  - high: 1.0
    log: true
    low: 0.1
    name: rf_max_features
    type: float
  - high: 20
    low: 1
    name: rf_min_samples_leaf
    type: int
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: sgd-classifier
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - choices:
    - log
    - modified_huber
    name: sgd_loss
    type: categorical
  - choices:
    - l1
    - l2
    - elasticnet
    name: sgd_penalty
    type: categorical
  - high: 0.1
    log: true
    low: 1.0e-07
    name: sgd_alpha
    type: float
  - choices:
    - optimal
    - invscaling
    - constant
    name: sgd_learning_rate
    type: categorical
  - high: 1
    log: true
    low: 1.0e-09
    name: sgd_l1_ratio
    type: float
  - high: 0.1
    log: true
    low: 1.0e-07
    name: sgd_eta0
    type: float
  - high: 1
    log: true
    low: 1.0e-05
    name: sgd_power_t
    type: float
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: svc
  namespace: modela-catalog
spec:
  frameworkName: scikit-learn
  ranges:
  - high: 32768
    log: true
    low: 0.03125
    name: svc_C
    type: float
  - choices:
    - rbf
    - poly
    - sigmoid
    name: svc_kernel
    type: categorical
  - high: 5
    low: 2
    name: svc_degree
    type: int
  - high: 8
    log: true
    low: 3.0517578125e-05
    name: svc_gamma
    type: float
  - high: 1
    log: true
    low: -1
    name: svc_coef0
    type: float
  - choices:
    - "true"
    - "false"
    name: svc_shrinking
    type: categorical
  - high: 0.1
    log: true
    low: 1.0e-05
    name: svc_tol
    type: float
  tasks:
  - multi-classification
  - binary-classification

---
apiVersion: catalog.modela.ai/v1alpha1
kind: Algorithm
metadata:
  labels:
    app.kubernetes.io/part-of: modela
  name: xgboost-classifier
  namespace: modela-catalog
spec:
  frameworkName: xgboost
  ranges:
  - high: 1024
    log: true
    low: 64
    name: xgb_num_round
    type: float
  - high: 8
    low: 2
    name: xgb_max_depth
    type: int
  - high: 1
    log: true
    low: 0.01
    name: xgb_eta
    type: float
  - high: 64.0
    log: true
    low: 1.0e-06
    name: xgb_gamma
    type: float
  - high: 32.0
    log: true
    low: 1.0e-06
    name: xgb_min_child_weight
    type: float
  - high: 1.0
    log: true
    low: 0.5
    name: xgb_subsample
    type: float
  - high: 1.0
    log: true
    low: 0.3
    name: xgb_colsample_bytree
    type: float
  - high: 2.0
    log: true
    low: 1.0e-06
    name: xgb_lambda
    type: float
  - high: 2.0
    log: true
    low: 1.0e-06
    name: xgb_alpha
    type: float
  - high: 0.01
    log: true
    low: 1.0e-06
    name: xgb_learning_rate
    type: float
  tasks:
  - multi-classification
  - binary-classification
